<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.12</version>
		<relativePath/>
	</parent>

	<groupId>cn.shopex</groupId>
	<artifactId>ecshopx</artifactId>
	<version>${revision}</version>
	<packaging>pom</packaging>
	<name>ecshopx</name>
	<description>Ecshopx Java</description>

	<properties>
		<revision>5.1.0</revision>
		<java.version>17</java.version>
		<mybatis-plus.version>3.5.16</mybatis-plus.version>
		<lombok.version>1.18.36</lombok.version>
		<jjwt.version>0.12.6</jjwt.version>
		<zxing.version>3.5.3</zxing.version>
		<wxjava.version>4.7.6-20250628.205748</wxjava.version>
		<alipay-sdk.version>4.39.134.ALL</alipay-sdk.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-common</artifactId>
				<version>${wxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-miniapp</artifactId>
				<version>${wxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-open</artifactId>
				<version>${wxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-mp</artifactId>
				<version>${wxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-cp</artifactId>
				<version>${wxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.binarywang</groupId>
				<artifactId>weixin-java-pay</artifactId>
				<version>${wxjava.version}</version>
			</dependency>
			<dependency>
				<groupId>com.alipay.sdk</groupId>
				<artifactId>alipay-sdk-java</artifactId>
				<version>${alipay-sdk.version}</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-spring-boot3-starter</artifactId>
				<version>${mybatis-plus.version}</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-jsqlparser</artifactId>
				<version>${mybatis-plus.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-dispatch</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-adapay</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-aftersales</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-ali</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-aliyunsms</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-bspay</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-chinaums-pay</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-comments</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-community</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-companys</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-cross-border</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-data-cube</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-deposit</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-distribution</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-employee-purchase</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-espier</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-form</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-goods</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-hfpay</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-im</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-kaquan</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-kujiale</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-members</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-merchant</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-one-code</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-openapi</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-orders</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-payment</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-point</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-pointsmall</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-popularize</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-promotions</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-reservation</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-salesperson</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-selfservice</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-shopex-ai</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-shopmenu-border</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-shuyun</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-super-admin</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-supplier</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-system-link</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-tb-items</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-tdkset</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-theme</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-third-party</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-wechat</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-work-wechat</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-wsugc</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.shopex</groupId>
				<artifactId>ecshopx-youshu</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt-api</artifactId>
				<version>${jjwt.version}</version>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt-impl</artifactId>
				<version>${jjwt.version}</version>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt-jackson</artifactId>
				<version>${jjwt.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.zxing</groupId>
				<artifactId>core</artifactId>
				<version>${zxing.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.zxing</groupId>
				<artifactId>javase</artifactId>
				<version>${zxing.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<modules>
		<module>ecshopx-bom</module>
		<module>ecshopx-common</module>
		<module>ecshopx-dispatch</module>
		<module>ecshopx-bootstrap</module>
		<module>ecshopx-adapay</module>
		<module>ecshopx-aftersales</module>
		<module>ecshopx-ali</module>
		<module>ecshopx-aliyunsms</module>
		<module>ecshopx-bspay</module>
		<module>ecshopx-chinaums-pay</module>
		<module>ecshopx-comments</module>
		<module>ecshopx-community</module>
		<module>ecshopx-companys</module>
		<module>ecshopx-cross-border</module>
		<module>ecshopx-data-cube</module>
		<module>ecshopx-deposit</module>
		<module>ecshopx-distribution</module>
		<module>ecshopx-employee-purchase</module>
		<module>ecshopx-espier</module>
		<module>ecshopx-form</module>
		<module>ecshopx-goods</module>
		<module>ecshopx-hfpay</module>
		<module>ecshopx-im</module>
		<module>ecshopx-kaquan</module>
		<module>ecshopx-kujiale</module>
		<module>ecshopx-members</module>
		<module>ecshopx-merchant</module>
		<module>ecshopx-one-code</module>
		<module>ecshopx-openapi</module>
		<module>ecshopx-orders</module>
		<module>ecshopx-payment</module>
		<module>ecshopx-point</module>
		<module>ecshopx-pointsmall</module>
		<module>ecshopx-popularize</module>
		<module>ecshopx-promotions</module>
		<module>ecshopx-reservation</module>
		<module>ecshopx-salesperson</module>
		<module>ecshopx-selfservice</module>
		<module>ecshopx-shopex-ai</module>
		<module>ecshopx-shopmenu-border</module>
		<module>ecshopx-shuyun</module>
		<module>ecshopx-super-admin</module>
		<module>ecshopx-supplier</module>
		<module>ecshopx-system-link</module>
		<module>ecshopx-tb-items</module>
		<module>ecshopx-tdkset</module>
		<module>ecshopx-theme</module>
		<module>ecshopx-third-party</module>
		<module>ecshopx-wechat</module>
		<module>ecshopx-work-wechat</module>
		<module>ecshopx-wsugc</module>
		<module>ecshopx-youshu</module>
	</modules>

	<repositories>
		<repository>
			<id>aliyun-public</id>
			<url>https://maven.aliyun.com/repository/public</url>
			<releases><enabled>true</enabled></releases>
			<snapshots><enabled>false</enabled></snapshots>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>1.6.0</version>
				<configuration>
					<updatePomFile>true</updatePomFile>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
				</configuration>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
